### ISSUE TITLE
I cannot update my mod list

### ISSUE THREAD

**Issue by KCisSICKnasty** [phinocio/loadorderlibrary-frontend#14]
I managed to post my load order, but now I cannot update it. It's doing what it did before when I tried to post. It hangs and never updates, as if I never clicked it. No loading or anything. I can't even click home page, I have to full refresh the site.

**Comment by phinocio** [comment]
Only thing I can think of is the same clear data thing as the other issue. Never been able to reproduce this myself either :(.

Also if you open the console (Ctrl+Shift+J or Cmd+Shift+J on Mac), is there any errors in it?

**Comment by KCisSICKnasty** [comment]
Actually, the whole site is just back to not letting me log in again so I'll have to clear data again. :/

My Load Order also must've been removed in the non-update process because i'm getting error 503.
As for errors, yes. The site is down error 500. It got worse as I typed this. O_o

**Comment by phinocio** [comment]
Current 500 error and 503 from the API is me redoing infra a bit, so the site will be sporadically offline for the next bit haha

**Comment by KCisSICKnasty** [comment]
9.B8Uj1PnS.js:7 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at W (9.B8Uj1PnS.js:7:322)
    at pe (9.B8Uj1PnS.js:7:344)
    at De (index.CXuAJut_.js:1:5924)
    at new ye (9.B8Uj1PnS.js:7:3136)
    at we (index.CXuAJut_.js:1:4533)
    at Object.p (app.DYq3_uI_.js:2:4159)
    at F (26.CYgV56HL.js:1:972)
    at Object.p (2.D3BxmFv4.js:16:9137)
    at M (26.CYgV56HL.js:1:2041)
    at z (26.CYgV56HL.js:1:1696)

I managed to get this.

**Comment by KCisSICKnasty** [comment]
Oh, okay. xD

**Comment by KCisSICKnasty** [comment]
Yeah, I tried running the same thing with inspect and clearing. It's consistent, every time I go to update, it hangs on update and does nothing, and then the site is broken. :/ Clearing with inspect lets me login and view mod lists, but I cant do anything with my own. :(

**Comment by KCisSICKnasty** [comment]
Update: It extends to other browsers. I tried to do it on another and same business. I click Update, it doesn't update, and I have to refresh the page to get the site to work again.

**Comment by phinocio** [comment]
That's so weird. I'll try to look into it more when I have more time this weekend

**Comment by KCisSICKnasty** [comment]
I patiently await~ (:

**Comment by phinocio** [comment]
I did some stuff late last week, and just fixed another big issue...maybe try again when you get a chance

**Comment by KCisSICKnasty** [comment]
Cleared the data and posted my update. (: 
Appreciate all your hard work!
